/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package petshop;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.Hashtable;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Kawsar Ahmed
 */
public class Cart extends javax.swing.JFrame {

    private String userName;
    private DBConnection conn;
    private static DecimalFormat df = new DecimalFormat("0.00");
    private Hashtable<Integer, Integer> my_dict;
    
    public Cart(String username) {
        this.my_dict = new Hashtable<Integer, Integer>();
        conn = new DBConnection();
        initComponents();
        
        this.userName = username;
        
        CreateTable();
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        SubtotalTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        TaxTextField = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        TotalTextField = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        KeepShoppingButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LogoutButton = new javax.swing.JButton();
        CheckoutButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        InventoryTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(62, 180, 137));

        jPanel4.setBackground(new java.awt.Color(0, 51, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Subtotal:");

        SubtotalTextField.setEditable(false);
        SubtotalTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SubtotalTextField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        SubtotalTextField.setText("0.00");

        jLabel4.setBackground(new java.awt.Color(51, 51, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tax:");

        TaxTextField.setEditable(false);
        TaxTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TaxTextField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        TaxTextField.setText("0.00");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total:");

        TotalTextField.setEditable(false);
        TotalTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TotalTextField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        TotalTextField.setText("0.00");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 11, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(TotalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(TaxTextField))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(SubtotalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubtotalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TotalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        KeepShoppingButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        KeepShoppingButton.setText("Keep Shopping");
        KeepShoppingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeepShoppingButtonActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 51, 255));

        jLabel1.setFont(new java.awt.Font("Snap ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cart");

        LogoutButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoutButton)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogoutButton))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        CheckoutButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CheckoutButton.setText("Checkout");
        CheckoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckoutButtonActionPerformed(evt);
            }
        });

        InventoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Price", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        InventoryTable.getTableHeader().setReorderingAllowed(false);
        InventoryTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InventoryTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(InventoryTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(KeepShoppingButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CheckoutButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(KeepShoppingButton)
                        .addGap(28, 28, 28)
                        .addComponent(CheckoutButton)
                        .addGap(48, 48, 48))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void KeepShoppingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeepShoppingButtonActionPerformed
        
        this.setVisible(false);dispose();

        Products dashBoardInstance = new Products(this);
        dashBoardInstance.setLocationRelativeTo(null);
        dashBoardInstance.setTitle("Dashboard");
        dashBoardInstance.setVisible(true);
    }//GEN-LAST:event_KeepShoppingButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        dispose();
        this.setVisible(false);

        Login newLoginInstance = new Login();
        newLoginInstance.setLocationRelativeTo(null);
        newLoginInstance.setTitle("Login");
        newLoginInstance.setVisible(true);
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void CheckoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckoutButtonActionPerformed
        if(Double.parseDouble(TotalTextField.getText()) == 0) {
            JOptionPane.showMessageDialog(this, "Please add items to cart prior to checkout.", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            InsertIntoSalesTable();
            UpdateInventoryTable();
            DropShoppingCartTable();
            ResetTotals();
            JOptionPane.showMessageDialog(this, "Checkout complete. Items are on the way.", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);

            dispose();
            this.setVisible(false);

            Cart ShoppingCartInstance = new Cart(this.userName);
            Products dashBoardInstance = new Products(ShoppingCartInstance);
            dashBoardInstance.setLocationRelativeTo(null);
            dashBoardInstance.setTitle("Dashboard");
            dashBoardInstance.setVisible(true);
        }
    }//GEN-LAST:event_CheckoutButtonActionPerformed

    private void InventoryTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventoryTableMouseClicked
        if (evt.getClickCount() == 2 ) {
            int index        = InventoryTable.getSelectedRow();
            TableModel model = InventoryTable.getModel();

            int itemId = (int) model.getValueAt(index, 0);

//            ItemDetails itemDetailsInstance = new ItemDetails(itemId);
//            itemDetailsInstance.setLocationRelativeTo(null);
//            itemDetailsInstance.setTitle("Item Details");
//            itemDetailsInstance.setVisible(true);
        }
    }//GEN-LAST:event_InventoryTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cart("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckoutButton;
    private javax.swing.JTable InventoryTable;
    private javax.swing.JButton KeepShoppingButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JTextField SubtotalTextField;
    private javax.swing.JTextField TaxTextField;
    private javax.swing.JTextField TotalTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables

    
    public void addRowToJTable() {
        DefaultTableModel model = (DefaultTableModel) InventoryTable.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        Object rowData[] = new Object[4];
        
        java.sql.Connection dbconn = conn.connectDB();
        
        try {
            PreparedStatement st = dbconn.prepareStatement("SELECT * FROM " + this.getTableName() + " ORDER BY PId ASC");

            ResultSet res = st.executeQuery();

            while(res.next()) {
                rowData[0] = res.getInt("PId");
                rowData[1] = res.getString("PName");
                rowData[2] = res.getDouble("Pprice");
                rowData[3] = res.getInt("Pqty");
        
                model.addRow(rowData);
            }
            
            res.close();
            st.close();
            
        } catch (SQLException ex) {
            //java.util.logging.Logger.getLogger(AdminPanelHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }  
        
        UpdateTotals();
    }

    

     private void InsertIntoSalesTable() {
        Connection dbconn = conn.connectDB();
        
        try {
            PreparedStatement st = dbconn.prepareStatement("INSERT INTO sales (username, total) VALUES (?, ?)");
            
            st.setString(1, this.userName);
            st.setDouble(2, Double.parseDouble(TotalTextField.getText()));

            int res = st.executeUpdate();
            st.close();
            
        } catch (SQLException ex) {
           // java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
    }

    

    private void DropShoppingCartTable() {
        Connection dbconn = conn.connectDB();

        try {
            PreparedStatement st = dbconn.prepareStatement("DROP TABLE " + this.getTableName());
            
            int res = st.executeUpdate();

            st.close();

        } catch (SQLException ex) {
            //java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    private void ResetTotals() {
        SubtotalTextField.setText(String.valueOf(0.00));
        TaxTextField.setText(String.valueOf(0.00));
        TotalTextField.setText(String.valueOf(0.00));
    }
     private void CreateTable() {
        Connection dbconn = conn.connectDB();
        
        try {
            PreparedStatement st = dbconn.prepareStatement("CREATE TABLE IF NOT EXISTS " + userName + "_cart AS SELECT PId, PName, Pprice, Pqty FROM pettbl LIMIT 0" );

            int res = st.executeUpdate();

            st.close();

        } catch (SQLException ex) {
            //java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
     public String getTableName() { return userName + "_cart"; }
     
     public void AddToCart(int itemId, String itemName, double itemPrice, int quantity) {
        Connection dbconn = conn.connectDB();
        
        try {
            PreparedStatement st = dbconn.prepareStatement("INSERT INTO " + this.getTableName() + " (PId, PName, Pprice, Pqty) VALUES (?, ?, ?, ?)");

            st.setInt(1, itemId);
            st.setString(2, itemName);
            st.setDouble(3, itemPrice);
            st.setInt(4, quantity);
            
            int res = st.executeUpdate();

            st.close();

        } catch (SQLException ex) {
            //java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    
    public void UpdateTotals() {
        Object[] rowData = new Object [InventoryTable.getRowCount()];
        
        double subTotal = 0.00;

        for (int i = 0; i < InventoryTable.getRowCount(); i++) 
        {
            double a = (double) InventoryTable.getValueAt(i, 2);
            int b    = (int) InventoryTable.getValueAt(i, 3);
            subTotal += a * b;
        }
    
        double tax = subTotal * 0.07;
        double total = tax + subTotal;
        
        SubtotalTextField.setText(String.valueOf(df.format(subTotal)));
        TaxTextField.setText(String.valueOf(df.format(tax)));
        TotalTextField.setText(String.valueOf(df.format(total)));
    }
    
    private void ItemsInCart() {
        Connection dbconn = conn.connectDB();
        
        try {
            PreparedStatement st = dbconn.prepareStatement("SELECT PId, SUM(Pqty) AS Pqty FROM " + this.getTableName() + " GROUP BY 1");

            ResultSet res = st.executeQuery();

            while(res.next()) {
                my_dict.put(res.getInt("PId"), res.getInt("Pqty"));
            }
            
            res.close();
            st.close();

        } catch (SQLException ex) {
           // java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    
        public int QuantityByItemId(int itemId) {
        ItemsInCart();
        
        return my_dict.get(itemId) == null ? 0 : my_dict.get(itemId);
    }
    
    public void UpdateInventoryTable() {
        Connection dbconn = conn.connectDB();
        
        try {
                for (Map.Entry<Integer, Integer> item : my_dict.entrySet()) {    
                    PreparedStatement st = dbconn.prepareStatement("UPDATE pettbl SET Pqty = (Pqty - ?) WHERE PId = ?");

                    st.setInt(1, item.getValue());
                    st.setInt(2, item.getKey());
            
                    int res = st.executeUpdate();
                    
                    st.close();
                }
        } catch (SQLException ex) {
            //java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        my_dict.clear();
    
    }
    
    
}
