/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package petshop;


import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
public class ItemDetails extends javax.swing.JFrame {

    DBConnection conn;
    int itemId;
    private Cart CartInstance;
    public ItemDetails() {
        initComponents();
    }

     public ItemDetails(int itemId, Cart CartInstance) {
        initComponents();
        conn = new DBConnection();
        this.itemId = itemId;
        this.CartInstance = CartInstance;
        populateTextFields();
    }
     public void populateTextFields() {
        java.sql.Connection dbconn = conn.connectDB();
        
        try {
                PreparedStatement st = dbconn.prepareStatement("SELECT * FROM pettbl WHERE PId = ?");
            
                st.setInt(1, itemId);

                ResultSet res = st.executeQuery();

                if(res.next()) {
                    
                    ID_NameTextField1.setText(res.getString("PName"));
                    ID_PriceTextField1.setText(String.valueOf(res.getInt("Pprice")));
                   // ID_DescriptionTextField.setText(res.getString("description"));
                    
                } else {                   
                    JOptionPane.showMessageDialog(this, "Item not found.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            
                res.close();
                st.close();
            
        } catch (SQLException ex) {
           // java.util.logging.Logger.getLogger(AdminPanelHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ID_NameTextField1 = new javax.swing.JTextField();
        ID_NameLabel1 = new javax.swing.JLabel();
        ID_PriceLabel1 = new javax.swing.JLabel();
        ID_PriceTextField1 = new javax.swing.JTextField();
        QuantitySpinner1 = new javax.swing.JSpinner();
        ID_QuantityLabel1 = new javax.swing.JLabel();
        ID_DescriptionLabel1 = new javax.swing.JLabel();
        ID_DescriptionTextField1 = new javax.swing.JTextField();
        CancelButton1 = new javax.swing.JButton();
        ID_AddToCart1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(62, 180, 137));
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(0, 51, 255));

        jLabel2.setFont(new java.awt.Font("Snap ITC", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Items");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel1.setPreferredSize(new java.awt.Dimension(465, 400));
        jPanel1.setLayout(null);

        ID_NameTextField1.setEditable(false);
        ID_NameTextField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(ID_NameTextField1);
        ID_NameTextField1.setBounds(110, 30, 166, 21);

        ID_NameLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ID_NameLabel1.setText("Name");
        jPanel1.add(ID_NameLabel1);
        ID_NameLabel1.setBounds(10, 30, 80, 22);

        ID_PriceLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ID_PriceLabel1.setText("Price");
        jPanel1.add(ID_PriceLabel1);
        ID_PriceLabel1.setBounds(10, 60, 90, 22);

        ID_PriceTextField1.setEditable(false);
        ID_PriceTextField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ID_PriceTextField1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jPanel1.add(ID_PriceTextField1);
        ID_PriceTextField1.setBounds(110, 60, 166, 22);
        jPanel1.add(QuantitySpinner1);
        QuantitySpinner1.setBounds(110, 100, 41, 22);

        ID_QuantityLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ID_QuantityLabel1.setText("Quantity");
        jPanel1.add(ID_QuantityLabel1);
        ID_QuantityLabel1.setBounds(10, 100, 90, 23);

        ID_DescriptionLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ID_DescriptionLabel1.setText("Description");
        jPanel1.add(ID_DescriptionLabel1);
        ID_DescriptionLabel1.setBounds(10, 150, 103, 25);

        ID_DescriptionTextField1.setEditable(false);
        ID_DescriptionTextField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(ID_DescriptionTextField1);
        ID_DescriptionTextField1.setBounds(120, 150, 230, 57);

        CancelButton1.setBackground(new java.awt.Color(51, 51, 255));
        CancelButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CancelButton1.setForeground(new java.awt.Color(255, 255, 255));
        CancelButton1.setText("Close");
        CancelButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(CancelButton1);
        CancelButton1.setBounds(220, 250, 100, 24);

        ID_AddToCart1.setBackground(new java.awt.Color(0, 0, 255));
        ID_AddToCart1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ID_AddToCart1.setForeground(new java.awt.Color(255, 255, 255));
        ID_AddToCart1.setText("Add Item To Cart");
        ID_AddToCart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_AddToCart1ActionPerformed(evt);
            }
        });
        jPanel1.add(ID_AddToCart1);
        ID_AddToCart1.setBounds(10, 250, 160, 20);

        jLabel1.setBackground(new java.awt.Color(62, 180, 137));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshop/Images/background 1465x400.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 410, 310);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ID_AddToCart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_AddToCart1ActionPerformed
        int value = (Integer) QuantitySpinner1.getValue();

        if(value == 0) {
            JOptionPane.showMessageDialog(this, "Please add at least 1 unit.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            this.CartInstance.AddToCart(itemId, ID_NameTextField1.getText(), Double.parseDouble(ID_PriceTextField1.getText()), value);
            JOptionPane.showMessageDialog(this, "Item added to cart.", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_ID_AddToCart1ActionPerformed

    private void CancelButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButton1ActionPerformed
        dispose();
        this.setVisible(false);
    }//GEN-LAST:event_CancelButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItemDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton1;
    private javax.swing.JButton ID_AddToCart1;
    private javax.swing.JLabel ID_DescriptionLabel1;
    private javax.swing.JTextField ID_DescriptionTextField1;
    private javax.swing.JLabel ID_NameLabel1;
    private javax.swing.JTextField ID_NameTextField1;
    private javax.swing.JLabel ID_PriceLabel1;
    private javax.swing.JTextField ID_PriceTextField1;
    private javax.swing.JLabel ID_QuantityLabel1;
    private javax.swing.JSpinner QuantitySpinner1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
