/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package petshop;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Kawsar Ahmed
 */
public class Products extends javax.swing.JFrame {

    DBConnection conn;
    private Cart CartInstance;
    public Products(Cart ShoppingCartInstance) {
        initComponents();
        conn = new DBConnection();
        CartInstance = ShoppingCartInstance;
        addRowToJTable();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        InventoryTable = new javax.swing.JTable();
        AddToCartButton = new javax.swing.JButton();
        ViewCartButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        jLabel15.setBackground(new java.awt.Color(102, 102, 255));
        jLabel15.setFont(new java.awt.Font("Vivaldi", 3, 60)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Dream PetShop");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(180, 0, 420, 50);

        InventoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Price", "Quantity Available"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        InventoryTable.getTableHeader().setReorderingAllowed(false);
        InventoryTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InventoryTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(InventoryTable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(200, 140, 560, 270);

        AddToCartButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        AddToCartButton.setText("Add Item To Cart");
        AddToCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToCartButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AddToCartButton);
        AddToCartButton.setBounds(200, 430, 260, 30);

        ViewCartButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ViewCartButton.setText("View Cart");
        ViewCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewCartButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ViewCartButton);
        ViewCartButton.setBounds(600, 430, 160, 30);

        jLabel5.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshop/Images/logout-64.png"))); // NOI18N
        jLabel5.setText(" ");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 400, 60, 64);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshop/Images/productl__-_copy.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void InventoryTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventoryTableMouseClicked
        if (evt.getClickCount() == 2 ) {
            int index        = InventoryTable.getSelectedRow();
            TableModel model = InventoryTable.getModel();

            int itemId = (int) model.getValueAt(index, 0);

            ItemDetails itemDetailsInstance = new ItemDetails(itemId, CartInstance);
            itemDetailsInstance.setLocationRelativeTo(null);
            itemDetailsInstance.setTitle("Item Details");
            itemDetailsInstance.setVisible(true);
        }
    }//GEN-LAST:event_InventoryTableMouseClicked

    private void AddToCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToCartButtonActionPerformed
        int index        = InventoryTable.getSelectedRow();
        TableModel model = InventoryTable.getModel();

        if(index == -1) {
            JOptionPane.showMessageDialog(this, "Please select at least one item.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }else {
            int itemId       = (int) model.getValueAt(index, 0);
            String itemName  = (String) model.getValueAt(index, 1);
            double itemPrice = (double) model.getValueAt(index, 2);
            int quantity     = (int) model.getValueAt(index, 3);

            CartInstance.AddToCart(itemId, itemName, itemPrice, 1);

            JOptionPane.showMessageDialog(this, "Item added to cart.", "Success", JOptionPane.INFORMATION_MESSAGE);
            addRowToJTable();
        }
    }//GEN-LAST:event_AddToCartButtonActionPerformed

    private void ViewCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewCartButtonActionPerformed
        
        this.setVisible(false);dispose();

        CartInstance.addRowToJTable();
        CartInstance.setLocationRelativeTo(null);
        CartInstance.setTitle("Cart");
        CartInstance.setVisible(true);
    }//GEN-LAST:event_ViewCartButtonActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Products(new Cart ("kazol")).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddToCartButton;
    private javax.swing.JTable InventoryTable;
    private javax.swing.JButton ViewCartButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

private void addRowToJTable() {
        DefaultTableModel model = (DefaultTableModel) InventoryTable.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        Object rowData[] = new Object[4];
        
        java.sql.Connection dbconn = conn.connectDB();
        
        try {
            PreparedStatement st = dbconn.prepareStatement("SELECT * FROM pettbl ORDER BY PId ASC");

            ResultSet res = st.executeQuery();

            while(res.next()) {
                rowData[0] = res.getInt("PId");
                rowData[1] = res.getString("PName");
                rowData[2] = res.getDouble("Pprice");
                rowData[3] = res.getInt("Pqty") - CartInstance.QuantityByItemId(res.getInt("PId"));
        
                model.addRow(rowData);
            }
            
            res.close();
            st.close();
            
        } catch (SQLException ex) {
            //java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }        
    }

}
