/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package petshop;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import static java.time.Clock.system;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Kawsar Ahmed
 */
public class RegisterScreen extends javax.swing.JFrame {

    Connection con =null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    Statement st=null;
    public RegisterScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        FirstNameLabel = new javax.swing.JLabel();
        FirstNameTextField = new javax.swing.JTextField();
        AddressLabel = new javax.swing.JLabel();
        AddressTextField = new javax.swing.JTextField();
        UserNameLabel = new javax.swing.JLabel();
        phonenumbertb = new javax.swing.JTextField();
        PasswordLabel = new javax.swing.JLabel();
        BackToLoginButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        PasswordTextField1 = new javax.swing.JPasswordField();
        PasswordLabel1 = new javax.swing.JLabel();
        usernametextfield1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(830, 670));

        jPanel3.setLayout(null);

        FirstNameLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        FirstNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        FirstNameLabel.setText("Name");
        jPanel3.add(FirstNameLabel);
        FirstNameLabel.setBounds(230, 180, 150, 29);

        FirstNameTextField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        FirstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameTextFieldActionPerformed(evt);
            }
        });
        jPanel3.add(FirstNameTextField);
        FirstNameTextField.setBounds(410, 180, 200, 38);

        AddressLabel.setBackground(new java.awt.Color(51, 51, 255));
        AddressLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        AddressLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        AddressLabel.setText("Address");
        jPanel3.add(AddressLabel);
        AddressLabel.setBounds(230, 240, 140, 29);

        AddressTextField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AddressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressTextFieldActionPerformed(evt);
            }
        });
        jPanel3.add(AddressTextField);
        AddressTextField.setBounds(410, 230, 200, 38);

        UserNameLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        UserNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        UserNameLabel.setText("User Name");
        jPanel3.add(UserNameLabel);
        UserNameLabel.setBounds(200, 300, 180, 29);

        phonenumbertb.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        phonenumbertb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonenumbertbActionPerformed(evt);
            }
        });
        jPanel3.add(phonenumbertb);
        phonenumbertb.setBounds(410, 350, 200, 38);

        PasswordLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        PasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        PasswordLabel.setText("Phone");
        jPanel3.add(PasswordLabel);
        PasswordLabel.setBounds(220, 350, 150, 40);

        BackToLoginButton.setBackground(new java.awt.Color(0, 0, 255));
        BackToLoginButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BackToLoginButton.setForeground(new java.awt.Color(255, 255, 255));
        BackToLoginButton.setText("Login");
        BackToLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToLoginButtonActionPerformed(evt);
            }
        });
        jPanel3.add(BackToLoginButton);
        BackToLoginButton.setBounds(250, 480, 140, 39);

        registerButton.setBackground(new java.awt.Color(0, 0, 255));
        registerButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        jPanel3.add(registerButton);
        registerButton.setBounds(520, 480, 150, 39);

        jLabel14.setBackground(new java.awt.Color(102, 102, 255));
        jLabel14.setFont(new java.awt.Font("Vivaldi", 3, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 255));
        jLabel14.setText("Register Panel");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(310, 80, 220, 40);

        jLabel15.setBackground(new java.awt.Color(102, 102, 255));
        jLabel15.setFont(new java.awt.Font("Vivaldi", 3, 60)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Dream PetShop");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(200, 0, 430, 60);

        PasswordTextField1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        PasswordTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTextField1ActionPerformed(evt);
            }
        });
        jPanel3.add(PasswordTextField1);
        PasswordTextField1.setBounds(410, 410, 200, 38);

        PasswordLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        PasswordLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        PasswordLabel1.setText("Password");
        jPanel3.add(PasswordLabel1);
        PasswordLabel1.setBounds(220, 409, 150, 40);

        usernametextfield1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        usernametextfield1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernametextfield1ActionPerformed(evt);
            }
        });
        jPanel3.add(usernametextfield1);
        usernametextfield1.setBounds(410, 290, 200, 38);

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kawsar Ahmed\\Desktop\\kazol'\\close_48px.png")); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel13);
        jLabel13.setBounds(780, 0, 48, 48);

        jLabel1.setBackground(new java.awt.Color(0, 0, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshop/Images/catagory 830x670.jpg"))); // NOI18N
        jPanel3.add(jLabel1);
        jLabel1.setBounds(0, 0, 830, 670);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FirstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameTextFieldActionPerformed

    private void AddressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressTextFieldActionPerformed

    private void BackToLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToLoginButtonActionPerformed
        
         new Login().setVisible(true);
            this.dispose();
        
    }//GEN-LAST:event_BackToLoginButtonActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        String Name  = FirstNameTextField.getText();
        String address    = AddressTextField.getText();
        String user_name  = usernametextfield1.getText();
        String password   = PasswordTextField1.getText();
        String phone =phonenumbertb.getText();
       // boolean is_buyer   = buyerRadioButton.isSelected();
       // boolean is_seller  = sellerRadioButton.isSelected();

        if(Name.isEmpty() ||
            phone.isEmpty() ||
            address.isEmpty() ||
            user_name.isEmpty() ||
            password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please ensure that all fields all filled.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                userRegister (Name, address, user_name, phone , password) ;
            } catch (SQLException ex) {
                Logger.getLogger(RegisterScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
           
           
        }
    }//GEN-LAST:event_registerButtonActionPerformed

    private void phonenumbertbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonenumbertbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonenumbertbActionPerformed

    private void PasswordTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTextField1ActionPerformed

    private void usernametextfield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernametextfield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernametextfield1ActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        System.exit(0)  ;      // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JTextField AddressTextField;
    private javax.swing.JButton BackToLoginButton;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JTextField FirstNameTextField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JLabel PasswordLabel1;
    private javax.swing.JPasswordField PasswordTextField1;
    private javax.swing.JLabel UserNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField phonenumbertb;
    private javax.swing.JButton registerButton;
    private javax.swing.JTextField usernametextfield1;
    // End of variables declaration//GEN-END:variables
int itemId=0;
    Statement st1=null;
    ResultSet rs1=null;
    
    private void CountId() throws SQLException
    {
        st1=con.createStatement();
        rs1=st1.executeQuery("select Max(CustId)from customertbl");
        rs1.next();
        itemId=rs1.getInt(1)+1;
        
    }
    private void Countd() throws SQLException
    {
        st1=con.createStatement();
        rs1=st1.executeQuery("select Max(UId)from usertbl");
        rs1.next();
        itemId=rs1.getInt(1)+1;
        
    }
 private void userRegister(String Name,  String address, String user_name,String phone, String password ) throws SQLException {
         con=DriverManager.getConnection("jdbc:mysql://localhost:3306/petsop?zeroDateTimeBehavior=CONVERT_TO_NULL","root","amardesh");

        try {
                 pst = con.prepareStatement("SELECT * FROM usertbl WHERE Uname = ?");
            
                pst.setString(1, user_name);
                
                rs = pst.executeQuery();
                
                if(rs.next()) {
                    JOptionPane.showMessageDialog(this, "Username is already in use. Please choose another.", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                     //con=DriverManager.getConnection("jdbc:mysql://localhost:3306/petsop?zeroDateTimeBehavior=CONVERT_TO_NULL","root","amardesh");
                    CountId();
                    
                PreparedStatement Save =con.prepareStatement("insert into customertbl values(?,?,?,?)");
                Save.setInt(1, itemId);
                Save.setString(2,Name);
                Save.setString(3,address);
                Save.setString(4,phone);
                int row =Save.executeUpdate();
                //row.close();
                Save.close();
                //row.close();
                 //con=DriverManager.getConnection("jdbc:mysql://localhost:3306/petsop?zeroDateTimeBehavior=CONVERT_TO_NULL","root","amardesh");
                Countd();
                 Save =con.prepareStatement("insert into usertbl values(?,?,?)");
                Save.setInt(1, itemId);
                Save.setString(2,user_name);
                //Save.setString(3,addressTbl.getText());
                Save.setString(3,password);
                 row =Save.executeUpdate();          
               

                JOptionPane.showMessageDialog(this, "User account created.", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                    
                    FirstNameTextField.setText(null);
                   // MiddleNameTextField.setText(null);
                    phonenumbertb.setText(null);
                    AddressTextField.setText(null);
                    usernametextfield1.setText(null);
                    PasswordTextField1.setText(null);
                    
                    con.close();
                }
                
                rs.close();
                pst.close();
        } catch (SQLException ex) {
            //Logger.getLogger(LoginScreen.class.getName()).log(Level.SEVERE, null, ex);
       }
    }






}



