/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package petshop;

/**
 *
 * @author Kawsar Ahmed
 */
public class Splash_3 extends javax.swing.JFrame {

    //String name ;
    public Splash_3(String name) {
        initComponents();
        tt.setText(name+" , Nice to meet \n you!");
        //this.setVisible(true);
        try {
            for(int i=0;i<=100;i++){
                Thread.sleep(20);
                this.myprogressbar.setValue(i);
            }
        }
        catch (InterruptedException e){
            
        } 
        this.setVisible(false);
         this.dispose();
        Cart ShoppingCartInstance = new Cart(name);

                    Products dashBoardInstance = new Products (ShoppingCartInstance);
                    dashBoardInstance.setLocationRelativeTo(null);
                    dashBoardInstance.setTitle("Products");
                    dashBoardInstance.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tt = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        myprogressbar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(null);

        tt.setFont(new java.awt.Font("Snap ITC", 1, 36)); // NOI18N
        tt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(tt);
        tt.setBounds(0, 110, 500, 160);

        jLabel3.setFont(new java.awt.Font("Snap ITC", 1, 48)); // NOI18N
        jLabel3.setText("Hey");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 40, 110, 70);
        getContentPane().add(myprogressbar);
        myprogressbar.setBounds(0, 330, 500, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshop/Images/500x400.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Splash_3 mysplash=new Splash_3("");
        try {
            for(int i=0;i<=100;i++){
                Thread.sleep(20);
                mysplash.myprogressbar.setValue(i);
            }
        }
        catch (InterruptedException e){
            
        } 
        
                    Cart ShoppingCartInstance = new Cart("");

                    Products dashBoardInstance = new Products (ShoppingCartInstance);
                    dashBoardInstance.setLocationRelativeTo(null);
                    dashBoardInstance.setTitle("Products");
                    dashBoardInstance.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JProgressBar myprogressbar;
    private javax.swing.JLabel tt;
    // End of variables declaration//GEN-END:variables
}
